### ISSUE TITLE
Script 'scripts/snippet_shell.py' not found 

### ISSUE THREAD

**Issue by wolfgao** [google/mobly-bundled-snippets#124]
Hello, when I am tring to run "snippet_shell.py com.google.android.mobly.snippet.bundled" by following the instructions, I met error below:
pkg_resources.ResolutionError: Script 'scripts/snippet_shell.py' not found in metadata at '/usr/local/lib/python3.7/site-packages/mobly-1.9.1.dist-info'

What can I fix this problem?

Thanks,
Wolfgao

**Comment by xpconanfan** [comment]
this is something specific to your environment so we won't be able to help
