### ISSUE TITLE
test mutiple devices

### ISSUE THREAD

**Issue by ygw11223** [google/mobly-bundled-snippets#17]
I was trying to test two devices simultaneously but got confused because the shell only allow me to connect to one device. Could you please add more explanation about how to test multiple devices?

**Comment by dthkao** [comment]
Hi,
YGW, you have a few options:

First, if you are just testing out the features of the bundled snippets the easiest option might be to start a separate instance of the shell in another window for the second device. 

On the other hand, if you are looking to actually write automated multi device tests, you should take a look at the main mobly project (https://github.com/google/mobly) which provides the test running framework and the controllers for android devices (and snippet loading and control).

**Comment by ygw11223** [comment]
Got it. Thank you.
