### ISSUE TITLE
Add method to validate Internet connectivity

### ISSUE THREAD

**Issue by kdart** [google/mobly-bundled-snippets#74]
Could use a generic method to open a socket to an external site that can used instead of curl. This should be easy enough and will eliminate the need for curl on the device.

**Comment by xpconanfan** [comment]
This might be more difficult than it is.
Internet connectivity means different things for different use cases.
And the network APIs have been changing from version to version.

I think there's a NetworkDiagnostics class added in M for this purpose
Feel free to give this a try :)

**Comment by kdart** [comment]
Added in recent PR.
