### ISSUE TITLE
gradle sync failing

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly-bundled-snippets#84]
"Error:Conflict with dependency 'com.google.errorprone:error_prone_annotations' in project 'mobly-bundled-snippets'. Resolved versions for app (2.0.18) and test app (2.0.19) differ. See http://g.co/androidstudio/app-test-app-conflict for details."

Adding this seems to work around it:
`compile 'com.google.errorprone:error_prone_annotations:2.0.19'`

Not sure what's going on

**Comment by kdart** [comment]
Looks like this is generated by transitive dependencies. com.google.truth wants error_prone_annotations:2.0.19, but com.google.guava:guava:22.0-android want error_prone_annotations:2.0.18.

**Comment by kdart** [comment]
It turns out that is not the latest version, anyway. I updated the original PR and requested again. I don't see any problems.

**Comment by xpconanfan** [comment]
Fixed by #87
